-- Bus Booking System Database Schema for Docker MySQL
-- This runs automatically when MySQL container starts

USE bus_booking_system;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `phone` VARCHAR(15) UNIQUE NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('passenger', 'admin', 'super_admin') DEFAULT 'passenger',
  `status` ENUM('active', 'inactive', 'suspended') DEFAULT 'active',
  `refresh_token_hash` VARCHAR(255) NULL,
  `reset_token` VARCHAR(255) NULL,
  `reset_token_expiry` TIMESTAMP NULL,
  `is_email_verified` BOOLEAN DEFAULT FALSE,
  `email_verified_at` TIMESTAMP NULL,
  `last_login_at` TIMESTAMP NULL,
  `last_active_at` TIMESTAMP NULL,
  `profile_image` VARCHAR(500) NULL,
  `date_of_birth` DATE NULL,
  `address` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `country` VARCHAR(100) DEFAULT 'Nepal',
  `postal_code` VARCHAR(20) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  INDEX idx_email_phone (`email`, `phone`),
  INDEX idx_role_status (`role`, `status`),
  INDEX idx_created_at (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `buses` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `bus_number` VARCHAR(50) UNIQUE NOT NULL,
  `registration_number` VARCHAR(50) UNIQUE,
  `total_seats` INT NOT NULL,
  `seat_layout` JSON NOT NULL,
  `amenities` JSON,
  `bus_type` ENUM('Standard', 'Luxury', 'Sleeper', 'Mini') DEFAULT 'Standard',
  `status` ENUM('active', 'maintenance', 'retired') DEFAULT 'active',
  `manufacturer` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `year` INT NULL,
  `color` VARCHAR(50) NULL,
  `license_plate` VARCHAR(20) NULL,
  `insurance_expiry` DATE NULL,
  `fitness_expiry` DATE NULL,
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  INDEX idx_bus_number (`bus_number`),
  INDEX idx_bus_type (`bus_type`),
  INDEX idx_status (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `routes` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `origin` VARCHAR(100) NOT NULL,
  `destination` VARCHAR(100) NOT NULL,
  `distance_km` DECIMAL(10,2),
  `duration_minutes` INT,
  `base_price` DECIMAL(10,2),
  `is_active` BOOLEAN DEFAULT TRUE,
  `stops` JSON,
  `popularity_score` INT DEFAULT 0,
  `description` TEXT,
  `route_image` VARCHAR(500),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  UNIQUE KEY unique_route (origin, destination),
  INDEX idx_origin_destination (origin, destination),
  INDEX idx_is_active (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `schedules` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `bus_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `available_seats` INT NOT NULL,
  `total_seats` INT NOT NULL,
  `status` ENUM('scheduled', 'cancelled', 'completed', 'delayed') DEFAULT 'scheduled',
  `cancellation_reason` TEXT,
  `delay_minutes` INT DEFAULT 0,
  `driver_name` VARCHAR(100),
  `driver_phone` VARCHAR(15),
  `conductor_name` VARCHAR(100),
  `conductor_phone` VARCHAR(15),
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`bus_id`) REFERENCES `buses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`route_id`) REFERENCES `routes`(`id`) ON DELETE CASCADE,
  INDEX idx_departure_time (`departure_time`),
  INDEX idx_available_seats (`available_seats`),
  INDEX idx_bus_schedule (`bus_id`, `departure_time`),
  INDEX idx_route_schedule (`route_id`, `departure_time`),
  INDEX idx_status_departure (`status`, `departure_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bookings` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  `booking_reference` VARCHAR(50) UNIQUE NOT NULL,
  `selected_seats` JSON NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `status` ENUM('pending_payment', 'payment_processing', 'confirmed', 'cancelled', 'expired', 'refunded') DEFAULT 'pending_payment',
  `payment_gateway` ENUM('esewa', 'khalti', 'connectips'),
  `payment_reference` VARCHAR(255),
  `seat_lock_expires_at` TIMESTAMP NULL,
  `confirmed_at` TIMESTAMP NULL,
  `cancelled_at` TIMESTAMP NULL,
  `cancellation_reason` TEXT,
  `refund_amount` DECIMAL(10,2),
  `refund_processed_at` TIMESTAMP NULL,
  `passenger_details` JSON NOT NULL,
  `special_requests` TEXT,
  `ticket_downloaded` BOOLEAN DEFAULT FALSE,
  `ticket_downloaded_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
  FOREIGN KEY (`schedule_id`) REFERENCES `schedules`(`id`),
  INDEX idx_booking_reference (`booking_reference`),
  INDEX idx_status_lock_expiry (`status`, `seat_lock_expires_at`),
  INDEX idx_user_bookings (`user_id`, `created_at`),
  INDEX idx_schedule_bookings (`schedule_id`, `status`),
  INDEX idx_payment_reference (`payment_reference`),
  INDEX idx_created_at (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seat_locks` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `seat_number` VARCHAR(10) NOT NULL,
  `booking_id` INT NOT NULL,
  `locked_by` INT NOT NULL,
  `locked_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`schedule_id`) REFERENCES `schedules`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`locked_by`) REFERENCES `users`(`id`),
  UNIQUE KEY unique_schedule_seat (schedule_id, seat_number),
  INDEX idx_expiry_cleanup (`expires_at`),
  INDEX idx_booking_lock (`booking_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payment_transactions` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `gateway` ENUM('esewa', 'khalti', 'connectips') NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `request_payload` JSON,
  `response_payload` JSON,
  `status` ENUM('initiated', 'pending_verification', 'success', 'failed', 'refunded', 'cancelled') DEFAULT 'initiated',
  `transaction_id` VARCHAR(255),
  `error_message` TEXT,
  `payment_url` VARCHAR(500),
  `verification_attempts` INT DEFAULT 0,
  `last_verification_at` TIMESTAMP NULL,
  `refund_transaction_id` VARCHAR(255),
  `refunded_at` TIMESTAMP NULL,
  `ip_address` VARCHAR(45),
  `user_agent` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON DELETE CASCADE,
  INDEX idx_booking_payment (`booking_id`),
  INDEX idx_transaction_id (`transaction_id`),
  INDEX idx_gateway_status (`gateway`, `status`),
  INDEX idx_created_at (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `otp_codes` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `phone` VARCHAR(15) NOT NULL,
  `otp_code` VARCHAR(6) NOT NULL,
  `is_used` BOOLEAN DEFAULT FALSE,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_phone_otp (`phone`, `otp_code`),
  INDEX idx_expires_at (`expires_at`),
  INDEX idx_cleanup (`is_used`, `expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NULL,
  `action` VARCHAR(100) NOT NULL,
  `entity` VARCHAR(50) NOT NULL,
  `entity_id` INT,
  `old_values` JSON,
  `new_values` JSON,
  `ip_address` VARCHAR(45),
  `user_agent` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_audit (`user_id`),
  INDEX idx_entity_audit (`entity`, `entity_id`),
  INDEX idx_created_at (`created_at`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
